#################################
##             Main            ##
#################################


_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

#################################
##             Admin           ##
#################################

_admin:
    path:     /admin
    defaults: { _controller: AppBundle:Admin:index }

#################################
##             AJAX            ##
#################################
_get_users_ids:
    path:     /user/getAllIDs
    defaults: { _controller: AppBundle:User:getAllIDs }
    requirements:
        _format: json
        methods: GET

_get_user_info:
    path:     /user/getUserInfo/{id}
    defaults: { _controller: AppBundle:User:getUserInfo }
    requirements:
        _format: json
        methods: GET


#################################
##             User            ##
#################################

user:
    path:     /
    defaults: { _controller: "AppBundle:User:index" }

user_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:User:show" }

user_new:
    path:     /new
    defaults: { _controller: "AppBundle:User:new" }

user_create:
    path:     /create
    defaults: { _controller: "AppBundle:User:create" }
    methods:  POST

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:User:edit" }

user_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:User:update" }
    methods:  [POST, PUT]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:User:delete" }


